import React, { useState, useEffect, useRef } from 'react';
import {
  X,
  Send,
  Wrench,
  Sparkles,
  AlertTriangle,
  CheckCircle2,
  Play,
  Zap,
  Activity,
  ArrowRight,
  Check,
  Plus,
  Layers,
  Bot,
  Copy,
  Clock,
  Workflow as WorkflowIcon,
  ShieldCheck,
  FileSpreadsheet,
  Mail,
  MessageSquare,
  Globe,
  RotateCw
} from 'lucide-react';
import { Workflow, WorkflowNodeData, WorkflowConnection, Execution } from '../../types/workflow';
import { diagnoseWorkflow, autoRepairWorkflow, DiagnosticReport } from '../../utils/workflowDoctor';
import {
  detectUserLanguage,
  isWorkflowGenerationPrompt,
  synthesizeWorkflowFromPrompt,
} from '../../utils/workflowSynthesizer';
import {
  auditWorkflowDataCompleteness,
  extractNodeConfigFromText,
  fillDemoDataForWorkflow,
} from '../../utils/workflowDataAuditor';

interface BuiltWorkflowPreview {
  name: string;
  description: string;
  nodes: WorkflowNodeData[];
  connections: WorkflowConnection[];
}

interface AiFixerDrawerProps {
  isOpen: boolean;
  workflow: Workflow;
  latestExecution?: Execution | null;
  onClose: () => void;
  onUpdateWorkflow: (updated: Workflow, reason?: string) => void;
  onTestWorkflow?: () => void;
  onCreateNewWorkflow?: (
    name?: string,
    description?: string,
    starterNodes?: WorkflowNodeData[],
    starterConnections?: WorkflowConnection[]
  ) => Promise<void> | void;
}

interface ChatMessage {
  id: string;
  sender: 'user' | 'fixer';
  text: string;
  timestamp: string;
  language?: 'en' | 'hi';
  builtWorkflow?: BuiltWorkflowPreview;
  actions?: {
    label: string;
    actionType: 'auto_fix' | 'test_run' | 'apply_workflow' | 'create_new_workflow' | 'fill_demo_data';
  }[];
}

export const AiFixerDrawer: React.FC<AiFixerDrawerProps> = ({
  isOpen,
  workflow,
  latestExecution,
  onClose,
  onUpdateWorkflow,
  onTestWorkflow,
  onCreateNewWorkflow,
}) => {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [inputText, setInputText] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [userLang, setUserLang] = useState<'en' | 'hi'>('en');
  const [appliedWfId, setAppliedWfId] = useState<string | null>(null);
  const [report, setReport] = useState<DiagnosticReport>(() => diagnoseWorkflow(workflow, latestExecution, 'en'));
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Recalculate diagnostics whenever workflow, execution or language changes
  useEffect(() => {
    const diag = diagnoseWorkflow(workflow, latestExecution, userLang);
    setReport(diag);
  }, [workflow, latestExecution, userLang]);

  // Initial welcome message from AI Fixer
  useEffect(() => {
    if (isOpen && messages.length === 0) {
      const diag = diagnoseWorkflow(workflow, latestExecution, 'en');
      const issueCount = diag.issues.length;

      const welcomeText = `Hello & Namaste! I am **Build-Ai** ⚡, your autonomous Workflow Architect & Builder.

💬 **Ask me in English or Hindi / Mujhse English ya Hindi me poochein:**
• **Build Workflows Automatically**: Give me any instruction (e.g. *"Telegram notification workflow banao"* or *"Build Google Sheets lead outreach with Gmail"*), and I will place and connect the full workflow directly on your canvas!
• **Diagnose & Auto-Fix**: Fix broken connections, missing triggers, or node errors.

${
  issueCount === 0
    ? `✨ Your workflow **"${workflow.name}"** is 100% healthy! No issues detected.`
    : `⚠️ I detected **${issueCount} potential issue(s)** in **"${workflow.name}"**. Click **"⚡ Auto-Fix All"** or ask me to resolve them!`
}`;

      setMessages([
        {
          id: 'msg_welcome',
          sender: 'fixer',
          text: welcomeText,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          language: 'en',
          actions:
            issueCount > 0
              ? [
                  { label: '⚡ Auto-Fix All Problems', actionType: 'auto_fix' },
                  { label: '⚡ Execute Workflow', actionType: 'test_run' },
                ]
              : [{ label: '⚡ Execute Workflow', actionType: 'test_run' }],
        },
      ]);
    }
  }, [isOpen]);

  // Scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isLoading]);

  if (!isOpen) return null;

  // Directly apply a built workflow to current canvas
  const applyWorkflowToCanvasDirectly = (built: BuiltWorkflowPreview) => {
    const updatedWf: Workflow = {
      ...workflow,
      name: built.name,
      description: built.description,
      nodes: built.nodes,
      connections: built.connections,
    };

    onUpdateWorkflow(updatedWf, 'Generated by AI Fixer Robot');
    setAppliedWfId(built.name);
  };

  // Handle Auto-Repair internally
  const handleAutoRepair = (lang: 'en' | 'hi' = userLang) => {
    const { fixedWorkflow, fixesApplied } = autoRepairWorkflow(workflow, latestExecution, lang);

    onUpdateWorkflow(fixedWorkflow, 'AI Fixer Auto-Repair');

    // Immediately clear issues and update diagnostic report
    const freshDiag = diagnoseWorkflow(fixedWorkflow, null, lang);
    setReport(freshDiag);

    let replyText = '';
    if (lang === 'en') {
      replyText = `⚡ **Build-Ai Auto-Repair Completed! All Issues Resolved!**\n\n`;
      if (fixesApplied.length > 0) {
        replyText += `Here are the adjustments I made to your workflow:\n${fixesApplied
          .map((f) => `• ${f}`)
          .join('\n')}\n\n`;
      } else {
        replyText += `• Validated all node ports, connections, and execution states.\n\n`;
      }
      replyText += `✨ All issues have been cleared! Your workflow is 100% healthy and ready for testing.`;
    } else {
      replyText = `⚡ **Build-Ai Auto-Repair Complete! Sabhi Issues Remove Ho Gaye Hain!**\n\n`;
      if (fixesApplied.length > 0) {
        replyText += `Maine workflow me yeh adjustments kiye hain:\n${fixesApplied
          .map((f) => `• ${f}`)
          .join('\n')}\n\n`;
      } else {
        replyText += `• Sabhi ports, connections aur node parameters verify karke clear kar diye gaye hain.\n\n`;
      }
      replyText += `✨ Sabhi issues hata diye gaye hain! Workflow ab bilkul ready hai.`;
    }

    setMessages((prev) => [
      ...prev,
      {
        id: `repair_${Date.now()}`,
        sender: 'fixer',
        text: replyText,
        timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
        language: lang,
        actions: [{ label: '⚡ Execute Workflow Now', actionType: 'test_run' }],
      },
    ]);
  };

  // Send message to AI Fixer backend
  const handleSendMessage = async (textToSend?: string) => {
    const query = (textToSend || inputText).trim();
    if (!query || isLoading) return;

    const detected = detectUserLanguage(query);
    setUserLang(detected);

    const userMessage: ChatMessage = {
      id: `usr_${Date.now()}`,
      sender: 'user',
      text: query,
      timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
      language: detected,
    };

    setMessages((prev) => [...prev, userMessage]);
    setInputText('');
    setIsLoading(true);

    const lowerQuery = query.toLowerCase();

    // Only trigger immediate auto-repair if user explicitly commands it as an action
    if (lowerQuery === 'auto_fix' || lowerQuery === '/fix') {
      setTimeout(() => {
        handleAutoRepair(detected);
        setIsLoading(false);
      }, 300);
      return;
    }

    try {
      // Send request to AI Fixer backend with conversation history
      const historyPayload = messages.slice(-8).map((m) => ({
        role: m.sender === 'user' ? 'user' : 'model',
        text: m.text,
      }));

      const response = await fetch('/api/fixer/chat', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          message: query,
          workflow,
          latestExecution,
          language: detected,
          history: historyPayload,
        }),
      });

      if (!response.ok) {
        throw new Error(`Server returned HTTP ${response.status}`);
      }

      const data = await response.json();

      if (data.action === 'auto_repair' && data.builtWorkflow) {
        onUpdateWorkflow(
          {
            ...workflow,
            nodes: data.builtWorkflow.nodes,
            connections: data.builtWorkflow.connections,
          },
          'AI Fixer Auto-Repair'
        );
        handleAutoRepair(detected);
        setIsLoading(false);
        return;
      }

      if (data.action === 'update_node_config' && data.builtWorkflow) {
        onUpdateWorkflow(
          {
            ...workflow,
            name: data.builtWorkflow.name || workflow.name,
            description: data.builtWorkflow.description || workflow.description,
            nodes: data.builtWorkflow.nodes,
            connections: data.builtWorkflow.connections || workflow.connections,
          },
          'AI Fixer Node Configured'
        );

        setMessages((prev) => [
          ...prev,
          {
            id: `fixer_${Date.now()}`,
            sender: 'fixer',
            text: data.reply,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            language: detected,
            actions: data.actions || [{ label: '⚡ Execute Workflow Now', actionType: 'test_run' }],
          },
        ]);
        return;
      }

      if (data.action === 'build_workflow' && data.builtWorkflow?.nodes?.length) {
        const built = data.builtWorkflow;

        // Auto-apply directly to canvas
        applyWorkflowToCanvasDirectly(built);

        setMessages((prev) => [
          ...prev,
          {
            id: `fixer_${Date.now()}`,
            sender: 'fixer',
            text:
              data.reply ||
              (detected === 'en'
                ? `🚀 I have constructed and loaded the **"${built.name}"** workflow directly onto your canvas!`
                : `🚀 Maine aapka **"${built.name}"** workflow canvas par successfully construct aur load kar diya hai!`),
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            language: detected,
            builtWorkflow: built,
            actions: data.actions || [
              { label: '⚡ Fill Demo Data & Execute', actionType: 'fill_demo_data' },
              { label: '⚡ Execute Built Workflow', actionType: 'test_run' },
              { label: '✨ Create as Separate Workflow', actionType: 'create_new_workflow' },
            ],
          },
        ]);
      } else {
        // Standard chat response
        setMessages((prev) => [
          ...prev,
          {
            id: `fixer_${Date.now()}`,
            sender: 'fixer',
            text: data.reply || (detected === 'en' ? 'Understood!' : 'Samajh gaya!'),
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            language: detected,
            actions: data.actions || [
              { label: '⚡ Fill Demo Data & Execute', actionType: 'fill_demo_data' },
              { label: '⚡ Execute Workflow', actionType: 'test_run' },
            ],
          },
        ]);
      }
    } catch (err: any) {
      console.warn('[AI Fixer Drawer] Backend fallback:', err);

      // Local parameter extraction fallback
      const localExtraction = extractNodeConfigFromText(query, workflow);
      if (localExtraction.hasUpdates) {
        onUpdateWorkflow(localExtraction.updatedWorkflow, 'AI Fixer Local Node Configured');
        const audit = auditWorkflowDataCompleteness(localExtraction.updatedWorkflow, detected);
        const updateSummary = localExtraction.appliedUpdates
          .map((u) => `• **${u.nodeName}**: \`${u.key}\` = "${u.value}"`)
          .join('\n');

        let replyMsg = detected === 'en'
          ? `✓ **Node Configuration Saved!**\n\nI updated the parameters on your canvas:\n${updateSummary}\n\n`
          : `✓ **Node Parameters Save Ho Gaye!**\n\nMaine aapka data nodes me save kar diya hai:\n${updateSummary}\n\n`;

        if (audit.isComplete) {
          replyMsg += detected === 'en'
            ? `🎉 **Workflow is 100% complete and ready to run!** Click "Execute Workflow" below to run.`
            : `🎉 **Sabhi required details set ho chuki hain!** Workflow real me execute hone ke liye taiyar hai.`;
        } else {
          replyMsg += audit.promptText;
        }

        setMessages((prev) => [
          ...prev,
          {
            id: `fixer_${Date.now()}`,
            sender: 'fixer',
            text: replyMsg,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            language: detected,
            actions: [{ label: '⚡ Execute Workflow Now', actionType: 'test_run' }],
          },
        ]);
        return;
      }

      // Fallback synthesizer
      if (isWorkflowGenerationPrompt(query)) {
        const synth = synthesizeWorkflowFromPrompt(query, detected);
        applyWorkflowToCanvasDirectly(synth);
        const audit = auditWorkflowDataCompleteness(
          { ...workflow, nodes: synth.nodes, connections: synth.connections },
          detected
        );

        let synthReply = synth.explanation;
        if (!audit.isComplete) {
          synthReply += `\n\n${audit.promptText}`;
        }

        setMessages((prev) => [
          ...prev,
          {
            id: `fixer_${Date.now()}`,
            sender: 'fixer',
            text: synthReply,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            language: detected,
            builtWorkflow: {
              name: synth.name,
              description: synth.description,
              nodes: synth.nodes,
              connections: synth.connections,
            },
            actions: [
              { label: '⚡ Fill Demo Data & Execute', actionType: 'fill_demo_data' },
              { label: '⚡ Execute Built Workflow', actionType: 'test_run' },
            ],
          },
        ]);
      } else {
        const audit = auditWorkflowDataCompleteness(workflow, detected);
        setMessages((prev) => [
          ...prev,
          {
            id: `fixer_${Date.now()}`,
            sender: 'fixer',
            text: audit.isComplete
              ? (detected === 'en'
                  ? `I reviewed your workflow "${workflow.name}". All nodes are properly configured and ready for live execution!`
                  : `Maine aapka workflow "${workflow.name}" check kiya. Sabhi nodes configured hain aur real execution ke liye taiyar hain!`)
              : audit.promptText,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            language: detected,
            actions: [
              { label: '⚡ Fill Demo Data & Execute', actionType: 'fill_demo_data' },
              { label: '⚡ Execute Workflow', actionType: 'test_run' },
            ],
          },
        ]);
      }
    } finally {
      setIsLoading(false);
    }
  };

  const handleActionClick = async (actionType: string, msgBuiltWf?: BuiltWorkflowPreview) => {
    if (actionType === 'auto_fix') {
      handleAutoRepair();
    } else if (actionType === 'fill_demo_data') {
      const { updatedWorkflow, filledCount, summary } = fillDemoDataForWorkflow(workflow);
      onUpdateWorkflow(updatedWorkflow, 'AI Fixer Fill Demo Data');
      setMessages((prev) => [
        ...prev,
        {
          id: `demo_${Date.now()}`,
          sender: 'fixer',
          text:
            userLang === 'en'
              ? `✓ **Demo & Parameters Successfully Configured!**\n\nI populated working parameters across ${filledCount} field(s):\n${summary.map((s) => `• ${s}`).join('\n')}\n\n🎉 Ready to run! Click **"⚡ Execute Workflow Now"** below!`
              : `✓ **Demo Data Set Ho Gaya!**\n\nMaine ${filledCount} fields me working parameters configure kar diye hain:\n${summary.map((s) => `• ${s}`).join('\n')}\n\n🎉 Ab aap **"⚡ Execute Workflow Now"** par click karein aur execution dekhein!`,
          timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          language: userLang,
          actions: [{ label: '⚡ Execute Workflow Now', actionType: 'test_run' }],
        },
      ]);
    } else if (actionType === 'test_run') {
      if (onTestWorkflow) {
        onTestWorkflow();
        setMessages((prev) => [
          ...prev,
          {
            id: `test_${Date.now()}`,
            sender: 'fixer',
            text:
              userLang === 'en'
                ? `🚀 Execution initiated! Watch execution status chips directly on each canvas node.`
                : `🚀 Execution shuru ho gaya hai! Canvas par steps ke status chips update ho rahe hain.`,
            timestamp: new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
            language: userLang,
          },
        ]);
      }
    } else if (actionType === 'apply_workflow' && msgBuiltWf) {
      applyWorkflowToCanvasDirectly(msgBuiltWf);
    } else if (actionType === 'create_new_workflow' && msgBuiltWf) {
      if (onCreateNewWorkflow) {
        await onCreateNewWorkflow(
          msgBuiltWf.name,
          msgBuiltWf.description,
          msgBuiltWf.nodes,
          msgBuiltWf.connections
        );
        onClose();
      }
    }
  };

  return (
    <>
      {/* Backdrop */}
      <div
        className="fixed inset-0 bg-slate-950/70 backdrop-blur-sm z-50 transition-opacity animate-in fade-in"
        onClick={onClose}
      />

      {/* Slide-in AI Fixer Chat Drawer */}
      <div
        className="fixed top-0 right-0 bottom-0 w-full sm:w-[500px] max-w-full bg-[#0a0f1d] border-l border-cyan-500/30 shadow-2xl z-55 flex flex-col text-slate-100 animate-in slide-in-from-right duration-200"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="p-4 border-b border-slate-800/80 bg-slate-950/90 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div className="relative">
              {/* Build-Ai Avatar in Header */}
              <div className="w-10 h-10 rounded-2xl bg-gradient-to-tr from-cyan-500 via-teal-400 to-blue-600 flex items-center justify-center text-slate-950 shadow-md shadow-cyan-500/30">
                <Sparkles className="w-5 h-5 stroke-[2.4]" />
              </div>
              <span className="absolute -bottom-0.5 -right-0.5 w-3 h-3 rounded-full bg-emerald-400 border-2 border-slate-950 animate-pulse" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h3 className="text-sm font-bold text-white tracking-wide">Build-Ai</h3>
                <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-cyan-500/15 text-cyan-300 border border-cyan-500/30 flex items-center gap-1">
                  <Activity className="w-2.5 h-2.5 text-cyan-400 animate-pulse" />
                  AI Architect & Builder
                </span>
              </div>
              <p className="text-[11px] text-slate-400">
                {userLang === 'en'
                  ? 'Natural Language Builder • Auto-Repair & Architect'
                  : 'Natural Language Builder • Workflow Fixer & Architect'}
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            {/* Health Score Pill */}
            <div
              className={`px-2.5 py-1 rounded-lg text-xs font-mono font-bold flex items-center gap-1.5 border ${
                report.healthScore >= 85
                  ? 'bg-emerald-500/15 text-emerald-300 border-emerald-500/30'
                  : report.healthScore >= 50
                  ? 'bg-amber-500/15 text-amber-300 border-amber-500/30'
                  : 'bg-rose-500/15 text-rose-300 border-rose-500/30'
              }`}
              title="Workflow Health Score"
            >
              <span>{report.healthScore}%</span>
            </div>

            <button
              onClick={onClose}
              className="p-1.5 rounded-lg text-slate-400 hover:text-white hover:bg-slate-800 transition cursor-pointer"
              title="Close Build-Ai"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Quick Diagnostics Strip */}
        <div className="bg-slate-900/80 px-4 py-2.5 border-b border-slate-800/80 flex items-center justify-between gap-3 text-xs">
          <div className="flex items-center gap-2 min-w-0">
            {report.issues.length === 0 ? (
              <CheckCircle2 className="w-4 h-4 text-emerald-400 shrink-0" />
            ) : (
              <AlertTriangle className="w-4 h-4 text-amber-400 shrink-0" />
            )}
            <span className="truncate text-slate-300 font-medium">
              {report.issues.length === 0
                ? userLang === 'en'
                  ? 'Workflow healthy • All steps aligned'
                  : 'Workflow bilkul theek hai • Sabhi steps aligned'
                : userLang === 'en'
                ? `${report.issues.length} issue(s) detected in workflow`
                : `Workflow me ${report.issues.length} problem(s) mili hain`}
            </span>
          </div>

          {report.issues.length > 0 && (
            <button
              onClick={() => handleAutoRepair()}
              className="px-2.5 py-1 rounded-lg bg-gradient-to-r from-amber-500 to-orange-600 hover:from-amber-400 hover:to-orange-500 text-slate-950 font-bold text-xs flex items-center gap-1.5 shrink-0 shadow-sm transition active:scale-95 cursor-pointer"
            >
              <Wrench className="w-3.5 h-3.5" />
              <span>Auto-Fix All</span>
            </button>
          )}
        </div>

        {/* Chat Messages Body */}
        <div className="flex-1 overflow-y-auto p-4 space-y-4">
          {messages.map((msg) => {
            const isUser = msg.sender === 'user';
            return (
              <div
                key={msg.id}
                className={`flex gap-3 ${isUser ? 'flex-row-reverse' : 'flex-row'}`}
              >
                {!isUser ? (
                  <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-cyan-500 via-teal-400 to-blue-600 flex items-center justify-center text-slate-950 shrink-0 shadow-md">
                    <Sparkles className="w-4 h-4 stroke-[2.2]" />
                  </div>
                ) : (
                  <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-purple-500 to-indigo-600 flex items-center justify-center text-white shrink-0 shadow-md">
                    <span className="text-xs font-bold">U</span>
                  </div>
                )}

                <div className={`space-y-2 max-w-[85%] ${isUser ? 'items-end' : 'items-start'}`}>
                  <div className="flex items-center gap-2 text-[10px] text-slate-400 px-1">
                    <span>
                      {isUser ? (userLang === 'en' ? 'You' : 'Aap (User)') : 'Build-Ai'} • {msg.timestamp}
                    </span>
                  </div>

                  <div
                    className={`p-3.5 rounded-2xl text-xs leading-relaxed whitespace-pre-wrap ${
                      isUser
                        ? 'bg-gradient-to-br from-indigo-600 to-purple-700 text-white shadow-md rounded-tr-xs'
                        : 'bg-slate-900 border border-slate-800 text-slate-200 shadow-md rounded-tl-xs'
                    }`}
                  >
                    {msg.text}
                  </div>

                  {/* Built Workflow Node Preview Card */}
                  {msg.builtWorkflow && (
                    <div className="p-3 rounded-xl bg-slate-950 border border-cyan-500/40 space-y-2 shadow-lg">
                      <div className="flex items-center justify-between border-b border-slate-800 pb-2">
                        <div className="flex items-center gap-2">
                          <WorkflowIcon className="w-4 h-4 text-cyan-400" />
                          <span className="text-xs font-bold text-white">
                            {msg.builtWorkflow.name}
                          </span>
                        </div>
                        <span className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-cyan-950 text-cyan-300 border border-cyan-800">
                          {msg.builtWorkflow.nodes.length} steps
                        </span>
                      </div>

                      <div className="space-y-1.5 py-1">
                        {msg.builtWorkflow.nodes.map((n, idx) => (
                          <div
                            key={n.id}
                            className="flex items-center gap-2 text-[11px] text-slate-300 bg-slate-900/80 px-2 py-1.5 rounded-lg border border-slate-800/80"
                          >
                            <span className="w-4 h-4 rounded-full bg-cyan-500/20 text-cyan-300 flex items-center justify-center font-mono text-[9px] font-bold">
                              {idx + 1}
                            </span>
                            <span className="font-semibold text-slate-200">{n.name}</span>
                            <span className="text-[10px] text-slate-500 ml-auto font-mono">
                              {n.type}
                            </span>
                          </div>
                        ))}
                      </div>

                      <div className="pt-1 flex gap-2">
                        <button
                          onClick={() => handleActionClick('apply_workflow', msg.builtWorkflow)}
                          className="flex-1 py-1.5 rounded-lg bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 text-white font-bold text-[11px] flex items-center justify-center gap-1.5 shadow-sm transition active:scale-95 cursor-pointer"
                        >
                          {appliedWfId === msg.builtWorkflow.name ? (
                            <>
                              <Check className="w-3.5 h-3.5 text-emerald-300" />
                              <span>Loaded on Canvas</span>
                            </>
                          ) : (
                            <>
                              <Zap className="w-3.5 h-3.5 text-cyan-300" />
                              <span>Load on Current Canvas</span>
                            </>
                          )}
                        </button>
                      </div>
                    </div>
                  )}

                  {/* Action Buttons */}
                  {msg.actions && msg.actions.length > 0 && (
                    <div className="flex flex-wrap gap-1.5 pt-1">
                      {msg.actions.map((act, aIdx) => (
                        <button
                          key={aIdx}
                          onClick={() => handleActionClick(act.actionType, msg.builtWorkflow)}
                          className="px-2.5 py-1 rounded-xl bg-slate-800 hover:bg-slate-700 border border-slate-700 hover:border-cyan-500/50 text-cyan-300 text-[11px] font-medium transition cursor-pointer flex items-center gap-1.5 shadow-xs active:scale-95"
                        >
                          {act.actionType === 'auto_fix' ? (
                            <Wrench className="w-3 h-3 text-amber-400" />
                          ) : act.actionType === 'test_run' ? (
                            <Play className="w-3 h-3 text-emerald-400" />
                          ) : act.actionType === 'fill_demo_data' ? (
                            <Zap className="w-3 h-3 text-amber-300" />
                          ) : (
                            <Sparkles className="w-3 h-3 text-cyan-400" />
                          )}
                          <span>{act.label}</span>
                        </button>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            );
          })}

          {isLoading && (
            <div className="flex gap-3 items-center text-slate-400 text-xs py-2">
              <div className="w-8 h-8 rounded-xl bg-gradient-to-tr from-cyan-500 via-teal-400 to-blue-600 flex items-center justify-center text-slate-950 shrink-0 animate-pulse">
                <Sparkles className="w-4 h-4 stroke-[2.2]" />
              </div>
              <div className="flex items-center gap-1.5 text-cyan-300">
                <RotateCw className="w-3.5 h-3.5 animate-spin" />
                <span>
                  {userLang === 'en'
                    ? 'Build-Ai is inspecting & architecting...'
                    : 'Build-Ai workflow build aur check kar raha hai...'}
                </span>
              </div>
            </div>
          )}

          <div ref={messagesEndRef} />
        </div>

        {/* Quick Suggestion Chips */}
        <div className="px-4 py-2 border-t border-slate-800/80 bg-slate-950/60 flex items-center gap-2 overflow-x-auto no-scrollbar text-[11px]">
          <span className="text-slate-400 shrink-0 font-medium text-[10px]">
            {userLang === 'en' ? 'Ideas:' : 'Suggestions:'}
          </span>
          <button
            onClick={() => handleSendMessage('⚡ Auto-fix all issues in this workflow')}
            className="px-2.5 py-1 rounded-full bg-slate-900 hover:bg-slate-800 border border-slate-700/80 hover:border-amber-500/50 text-amber-300 shrink-0 transition cursor-pointer"
          >
            ⚡ Auto-Fix All Errors
          </button>
          <button
            onClick={() => handleSendMessage('Telegram notification workflow banao jab webhook trigger ho')}
            className="px-2.5 py-1 rounded-full bg-slate-900 hover:bg-slate-800 border border-slate-700/80 hover:border-cyan-500/50 text-cyan-300 shrink-0 transition cursor-pointer"
          >
            📱 Telegram Bot Flow Banao
          </button>
          <button
            onClick={() => handleSendMessage('Read rows from Google Sheets and send email with Gmail')}
            className="px-2.5 py-1 rounded-full bg-slate-900 hover:bg-slate-800 border border-slate-700/80 hover:border-cyan-500/50 text-cyan-300 shrink-0 transition cursor-pointer"
          >
            📊 Sheets to Gmail
          </button>
          <button
            onClick={() => handleSendMessage('Build an autonomous AI Support Agent with Webhook and Slack')}
            className="px-2.5 py-1 rounded-full bg-slate-900 hover:bg-slate-800 border border-slate-700/80 hover:border-cyan-500/50 text-cyan-300 shrink-0 transition cursor-pointer"
          >
            🤖 Autonomous AI Agent
          </button>
        </div>

        {/* Input Bar */}
        <div className="p-3 border-t border-slate-800/80 bg-slate-950">
          <form
            onSubmit={(e) => {
              e.preventDefault();
              handleSendMessage();
            }}
            className="flex items-center gap-2"
          >
            <input
              type="text"
              value={inputText}
              onChange={(e) => setInputText(e.target.value)}
              placeholder={
                userLang === 'en'
                  ? 'Ask Build-Ai or give workflow instructions (English or Hindi)...'
                  : 'Build-Ai se poochhein ya workflow banane ka instruction dein...'
              }
              className="flex-1 px-3.5 py-2.5 rounded-xl bg-slate-900 border border-slate-700/80 focus:border-cyan-400 focus:ring-1 focus:ring-cyan-400 text-xs text-white placeholder-slate-500 outline-none transition"
              disabled={isLoading}
            />

            <button
              type="submit"
              disabled={!inputText.trim() || isLoading}
              className="p-2.5 rounded-xl bg-gradient-to-r from-cyan-600 to-blue-600 hover:from-cyan-500 hover:to-blue-500 disabled:opacity-40 disabled:hover:from-cyan-600 disabled:hover:to-blue-600 text-white shadow-md transition active:scale-95 cursor-pointer shrink-0"
              title="Send to Build-Ai"
            >
              <Send className="w-4 h-4 stroke-[2.2]" />
            </button>
          </form>
        </div>
      </div>
    </>
  );
};
